export enum ItemType {
    Ammunition = "A",
    AmmunitionFuturistic = "AF",
    ArtisanTool = "AT",
    EldritchMachine = "EM",
    Explosive = "EXP",
    AdventuringGear = "G",
    GamingSet = "GS",
    HeavyArmor = "HA",
    Instrument = "INS",
    LightArmor = "LA",
    MeleeWeapon = "M",
    MediumArmor = "MA",
    Mount = "MNT",
    GenericVariant = "GV",
    Potion = "P",
    RangedWeapon = "R",
    Rod = "RD",
    Ring = "RG",
    Shield = "S",
    Scroll = "SC",
    SpellcastingFocus = "SCF",
    Other = "OTH",
    Tool = "T",
    TackAndHarness = "TAH",
    TradeGood = "TG",
    Treasure = "$",
    VehicleLand = "VEH",
    VehicleWater = "SHP",
    VehicleAir = "AIR",
    Wand = "WD"
}

export enum SpellSchool {
    Abjuration = "A",
    Conjuration = "C",
    Divination = "D",
    Enchantment = "E",
    Evocation = "V",
    Illusion = "I",
    Necromancy = "N",
    Transmutation = "T",
    Psychic = "P"
}